name: CI Pipeline

on:
  push:
    branches:
      - SEUNGJIN_test01
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests kafka-python
        pip install pytest

    - name: Test with pytest
      run: |
        python producer.py  ${{ secrets.API_KEY }}
